CREATE DATABASE NhapXuatKho

CREATE TABLE DMHANG(
	MaDM VARCHAR(10) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(50)
)
GO
CREATE TABLE THUONGHIEU(
	MaTH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTH NVARCHAR(50),
	TruSo NVARCHAR(50),
	Website NVARCHAR(50)
)
GO
CREATE TABLE VITRILUUTRU(
	MaVT VARCHAR(10) NOT NULL PRIMARY KEY
)
GO
CREATE TABLE MATHANG(
	MaMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenMH NVARCHAR(50),
	MaDM VARCHAR(10) REFERENCES dbo.DMHang,
	MaTH VARCHAR(10) REFERENCES dbo.ThuongHieu,
	NgayHHSD DATETIME,
	GiaThanh BIGINT
)
GO
CREATE TABLE KHO(
	MaKho VARCHAR(10) NOT NULL PRIMARY KEY,
	DiaChi NVARCHAR(50)
)
GO
CREATE TABLE THANHTOAN(
	MaTT VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTT NVARCHAR(50)
)
GO
CREATE TABLE KIEUDOITAC(
	MaKieuDT VARCHAR(10) NOT NULL PRIMARY KEY,
	TenKieuDT NVARCHAR(50)
)
GO
CREATE TABLE PHONGBAN(
	MaPB VARCHAR(10) NOT NULL PRIMARY KEY,
	TenPB NVARCHAR(50)
)
GO
CREATE TABLE CHUCNANG(
	MaChucNang VARCHAR(10) NOT NULL PRIMARY KEY,
	MoTa VARCHAR(20) NOT NULL
)
GO
CREATE TABLE DOITAC(
	MaDT VARCHAR(10) NOT NULL PRIMARY KEY,
	MaKieuDT VARCHAR(10) REFERENCES dbo.KieuDoiTac,
	MaChucNang VARCHAR(10) REFERENCES dbo.CHUCNANG,
	TenDT NVARCHAR(50),
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50)
)
GO
CREATE TABLE NHANVIEN(
	MaNV VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNV NVARCHAR(50),
	GioiTinh BIT,
	NgaySinh DATETIME,
	DiaChi NVARCHAR(100),
	ChucVu NVARCHAR(50),
	MaPB VARCHAR(10) REFERENCES dbo.PhongBan,
	MaChucNang varchar(10) REFERENCES dbo.CHUCNANG,
	SoDT VARCHAR(20),
	Email VARCHAR(50)
)

GO
CREATE TABLE TAIKHOAN(
	TenTK VARCHAR(20) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(20) NOT NULL,
	MaChucNang VARCHAR(10) REFERENCES dbo.CHUCNANG
)
GO
CREATE TABLE LOAIPHIEU(
	MaLoaiPhieu VARCHAR(10) NOT NULL PRIMARY KEY,
	TenLoaiPhieu NVARCHAR(50)
)
GO
CREATE TABLE VANCHUYEN(
	MaVC VARCHAR(10) NOT NULL PRIMARY KEY,
	TenVC NVARCHAR(50),
	NgayVC DATETIME,
	MaNV VARCHAR(10) REFERENCES dbo.NHANVIEN,
	GiaThanh BIGINT
)
GO
CREATE TABLE PHIEU(
	MaPhieu VARCHAR(10) NOT NULL PRIMARY KEY,
	TenPhieu NVARCHAR(50),
	MaLoaiPhieu VARCHAR(10) REFERENCES dbo.LoaiPhieu,
	MaDT VARCHAR(10) REFERENCES dbo.DoiTac,
	MaNV VARCHAR(10) REFERENCES dbo.NhanVien,
	MaTT VARCHAR(10) REFERENCES dbo.ThanhToan,
	MaKho VARCHAR(10) REFERENCES dbo.Kho,
	MaVT VARCHAR(10) REFERENCES dbo.ViTriLuuTru,
	MaVC VARCHAR(10) REFERENCES dbo.VanChuyen,
	Ngay DATETIME,
	TrangThaiXL BIT,
	TrangThaiTT BIT,
	TrangThaiVC BIT
)
GO
CREATE TABLE CHITIETPHIEU(
	MaPhieu VARCHAR(10) NOT NULL REFERENCES dbo.Phieu,
	MaMH VARCHAR(10) REFERENCES dbo.MatHang,
	SoLuong INT,
	GhiChu NVARCHAR(100)
)
GO
CREATE TABLE CHIETKHAU(
	MaCK VARCHAR(10) NOT NULL PRIMARY KEY,
	GiaTri FLOAT NOT NULL,
	GhiChu NVARCHAR(50)
)
GO
CREATE TABLE CHITIETCHIETKHAU(
	MaCK VARCHAR(10) REFERENCES dbo.ChietKhau,
	MaDT VARCHAR(10) REFERENCES dbo.DoiTac
)
GO

