CREATE DATABASE NhapXuatKho

CREATE TABLE DMHang(
	MaDM VARCHAR(10) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(50)
)
GO
CREATE TABLE ThuongHieu(
	MaTH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTH NVARCHAR(50),
	TruSo NVARCHAR(50),
	Website NVARCHAR(50)
)
GO
CREATE TABLE ViTriLuuTru(
	MaVT VARCHAR(10) NOT NULL PRIMARY KEY
)
GO
CREATE TABLE MatHang(
	MaMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenMH NVARCHAR(50),
	MaDM VARCHAR(10) REFERENCES dbo.DMHang,
	MaTH VARCHAR(10) REFERENCES dbo.ThuongHieu,
	NgayHHSD DATETIME,
	GiaThanh BIGINT
)
GO
CREATE TABLE Kho(
	MaKho VARCHAR(10) NOT NULL PRIMARY KEY,
	DiaChi NVARCHAR(50)
)
GO
CREATE TABLE ThanhToan(
	MaTT VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTT NVARCHAR(50)
)
GO
CREATE TABLE KieuDoiTac(
	MaKieuDT VARCHAR(10) NOT NULL PRIMARY KEY,
	TenKieuDT NVARCHAR(50)
)
GO
CREATE TABLE DoiTac(
	MaDT VARCHAR(10) NOT NULL PRIMARY KEY,
	MaKieuDT VARCHAR(10) REFERENCES dbo.KieuDoiTac,
	TenDT NVARCHAR(50),
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50)
)
GO
CREATE TABLE LoaiTaiKhoan(
	MaLTK VARCHAR(10) NOT NULL PRIMARY KEY,
	ChucNang VARCHAR(20) NOT NULL
)
GO
CREATE TABLE TaiKhoan(
	TenTK VARCHAR(20) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(20) NOT NULL,
	MaLTK VARCHAR(10) REFERENCES dbo.LoaiTaiKhoan
)
GO
CREATE TABLE PhongBan(
	MaPB VARCHAR(10) NOT NULL PRIMARY KEY,
	TenPB NVARCHAR(50)
)
GO
CREATE TABLE NhanVien(
	MaNV VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNV NVARCHAR(50),
	GioiTinh BIT,
	NgaySinh DATETIME,
	DiaChi NVARCHAR(100),
	ChucVu NVARCHAR(50),
	MaPB VARCHAR(10) REFERENCES dbo.PhongBan,
	SoDT VARCHAR(20),
	Email VARCHAR(50)
)
GO
CREATE TABLE ChiTietTaiKhoan(
	TenTK VARCHAR(20) REFERENCES dbo.TaiKhoan,
	MaNV VARCHAR(10) REFERENCES dbo.NhanVien,
	MaDT VARCHAR(10) REFERENCES dbo.DoiTac
)
GO
CREATE TABLE LoaiPhieu(
	MaLoaiPhieu VARCHAR(10) NOT NULL PRIMARY KEY,
	TenLoaiPhieu NVARCHAR(50)
)
GO
CREATE TABLE VanChuyen(
	MaVC VARCHAR(10) NOT NULL PRIMARY KEY,
	TenVC NVARCHAR(50),
	GiaThanh BIGINT
)
GO
CREATE TABLE Phieu(
	MaPhieu VARCHAR(10) NOT NULL PRIMARY KEY,
	TenPhieu NVARCHAR(50),
	MaLoaiPhieu VARCHAR(10) REFERENCES dbo.LoaiPhieu,
	MaDT VARCHAR(10) REFERENCES dbo.DoiTac,
	MaNV VARCHAR(10) REFERENCES dbo.NhanVien,
	MaTT VARCHAR(10) REFERENCES dbo.ThanhToan,
	MaKho VARCHAR(10) REFERENCES dbo.Kho,
	MaVT VARCHAR(10) REFERENCES dbo.ViTriLuuTru,
	MaVC VARCHAR(10) REFERENCES dbo.VanChuyen,
	Ngay DATETIME,
	TrangThaiXL BIT,
	TrangThaiTT BIT,
	TrangThaiVC BIT
)
GO
CREATE TABLE ChiTietPhieu(
	MaPhieu VARCHAR(10) NOT NULL REFERENCES dbo.Phieu,
	MaMH VARCHAR(10) REFERENCES dbo.MatHang,
	SoLuong INT,
	GhiChu NVARCHAR(100)
)
GO
CREATE TABLE ChietKhau(
	MaCK VARCHAR(10) NOT NULL PRIMARY KEY,
	GiaTri FLOAT NOT NULL,
	GhiChu NVARCHAR(50)
)
GO
CREATE TABLE ChiTietChietKhau(
	MaCK VARCHAR(10) REFERENCES dbo.ChietKhau,
	MaDT VARCHAR(10) REFERENCES dbo.DoiTac
)
GO

