CREATE DATABASE NhapXuatKho

CREATE TABLE DMHANG(
	MaDM VARCHAR(10) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(50)
)

CREATE TABLE THUONGHIEU(
	MaTH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTH NVARCHAR(50),
	TruSo NVARCHAR(50),
	Website NVARCHAR(50)
)

CREATE TABLE VITRILUUTRU(
	MaVT VARCHAR(10) NOT NULL PRIMARY KEY,
	MoTa NVARCHAR(20),
	KhaNangChua INT
)

CREATE TABLE MATHANG(
	MaMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenMH NVARCHAR(50),
	MaDM VARCHAR(10) REFERENCES dbo.DMHang,
	MaTH VARCHAR(10) REFERENCES dbo.ThuongHieu,
	DVT nVARCHAR(10),
	NgayHHSD date,
	GiaNhap BIGINT,
	GiaXuat BIGINT,
	MoTa NVARCHAR(100)
)

CREATE TABLE KHO(
	MaKho VARCHAR(10) NOT NULL PRIMARY KEY,
	DiaChi NVARCHAR(50)
)

CREATE TABLE PTTHANHTOAN(
	MaPTTT VARCHAR(10) NOT NULL PRIMARY KEY,
	TenPTTT NVARCHAR(50),
)

CREATE TABLE NHACUNGCAP(
	MaNCC VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNCC NVARCHAR(50),
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50)
)

CREATE TABLE TAIKHOANKH(
	Email VARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(50) 
)
CREATE TABLE TAIKHOANNV(
	Email VARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(50) 
)
CREATE TABLE NHANVIEN(
	MaNV VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNV NVARCHAR(50),
	ChucVu NVARCHAR(50),
	NgaySinh date,
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50) REFERENCES dbo.TAIKHOANNV,
)

CREATE TABLE KHACHHANG(
	MaKH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(50),
	NgaySinh date,	
	GioiTinh BIT,
	SoDT VARCHAR(20),
	Email VARCHAR(50) REFERENCES dbo.TAIKHOANKH,	
)

CREATE TABLE DIACHINHANHANG(
	MaDC VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNguoiNhan NVARCHAR(50),
	SoDT VARCHAR(20),
	Duong NVARCHAR(50),
	PhuongXa NVARCHAR(50),
	QuanHuyen NVARCHAR(50),
	TinhThanh NVARCHAR(50),
)

CREATE TABLE SODIACHI(
	MaKH VARCHAR(10) REFERENCES dbo.KHACHHANG,
	MaDC VARCHAR(10) REFERENCES dbo.DIACHI
)

CREATE TABLE PHIEUNHAP(
	MaPN VARCHAR(20) NOT NULL PRIMARY KEY,
	Ngay date,
	MaNCC VARCHAR(10) REFERENCES dbo.NHACUNGCAP,
	MaNV VARCHAR(10) REFERENCES dbo.NHANVIEN,
	MaTT VARCHAR(10) REFERENCES dbo.THANHTOAN,
	MaKho VARCHAR(10) REFERENCES dbo.KHO,
	TrangThaiXL NVARCHAR(10),
)

CREATE TABLE CHITIETPHIEU(
	MaPN VARCHAR(20) REFERENCES dbo.PHIEUNHAP,
	MaMH VARCHAR(10) REFERENCES dbo.MATHANG,
	SoLuong INT,
	HSD date,
	MaVT VARCHAR(10) REFERENCES dbo.VITRILUUTRU
)

CREATE TABLE DONHANG(
	MaDH VARCHAR(20) NOT NULL PRIMARY KEY,
	MaKH VARCHAR(10) REFERENCES dbo.KHACHHANG,
	MaPTTT VARCHAR(10) REFERENCES dbo.THANHTOAN,
	Ngay date,
	TrangThaiXL NVARCHAR(10),
)

CREATE TABLE CHITIETDONHANG(
	MaDH VARCHAR(20) REFERENCES dbo.DONHANG,
	MaMH VARCHAR(10) REFERENCES dbo.MATHANG,
	SoLuong INT,
)

CREATE TABLE MATHANGKHUYENMAI(
	MaMH VARCHAR(10) REFERENCES dbo.MATHANG,
	GiaTriKM FLOAT,
	NgayBD date,
	NgayKT date
)

CREATE TABLE CHIETKHAU(
	MaCK VARCHAR(10) NOT NULL PRIMARY KEY,
	GiaTri	INT,
)

CREATE TABLE TINHTHANH(
	MaTThanh VARCHAR(5) NOT NULL PRIMARY KEY,
	Ten NVARCHAR(50)
)

CREATE TABLE QUANHUYEN(
	MaQH VARCHAR(5) NOT NULL PRIMARY KEY,
	MATThanh VARCHAR(5) REFERENCES dbo.TINHTHANH,
	Ten NVARCHAR(50)
)

CREATE TABLE PHUONGXA(
	MaPX VARCHAR(5) NOT NULL PRIMARY KEY,
	MaQH VARCHAR(5) REFERENCES dbo.QUANHUYEN
	Ten NVARCHAR(50)
)	