CREATE DATABASE NhapXuatKho

CREATE TABLE DMHANG(
	MaDM VARCHAR(10) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(50)
)

CREATE TABLE THUONGHIEU(
	MaTH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTH NVARCHAR(50),
	AnhDaiDien IMAGE,
	TruSo NVARCHAR(50),
	Website NVARCHAR(50)
)

CREATE TABLE VITRILUUTRU(
	MaVT VARCHAR(10) NOT NULL PRIMARY KEY,
	MoTa NVARCHAR(20),
	KhaNangChua INT
)

CREATE TABLE MATHANG(
	MaMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenMH NVARCHAR(50),
	AnhDaiDien IMAGE,
	MaDM VARCHAR(10) REFERENCES dbo.DMHang,
	MaTH VARCHAR(10) REFERENCES dbo.ThuongHieu,
	DVT VARCHAR(10),
	NgayHHSD DATETIME,
	GiaNhap BIGINT,
	GiaXuat BIGINT,
	MoTa NVARCHAR(100)
)

CREATE TABLE KHO(
	MaKho VARCHAR(10) NOT NULL PRIMARY KEY,
	DiaChi NVARCHAR(50)
)

CREATE TABLE THANHTOAN(
	MaTT VARCHAR(10) NOT NULL PRIMARY KEY,
	TenTT NVARCHAR(50),
	AnhDaiDien IMAGE,
)

CREATE TABLE NHACUNGCAP(
	MaNCC VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNCC NVARCHAR(50),
	AnhDaiDien IMAGE,
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50)
)

CREATE TABLE CHUCNANG(
	MaCN VARCHAR(10) NOT NULL PRIMARY KEY,
	MoTa NVARCHAR(50),
)

CREATE TABLE TAIKHOAN(
	TenTK VARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(50) NOT NULL,
	MaCN VARCHAR(10) REFERENCES dbo.CHUCNANG,
)

CREATE TABLE KHACHHANG(
	MaKH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(50),
	MaCN VARCHAR(10) REFERENCES dbo.CHUCNANG,
	NgaySinh DATETIME,
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50),	
)

CREATE TABLE NHANVIEN(
	MaNV VARCHAR(10) NOT NULL PRIMARY KEY,
	TenNV NVARCHAR(50),
	ChucVu NVARCHAR(50),
	MaCN VARCHAR(10) REFERENCES dbo.CHUCNANG,
	NgaySinh DATETIME,
	GioiTinh BIT,
	DiaChi NVARCHAR(100),
	SoDT VARCHAR(20),
	Email VARCHAR(50),
)

CREATE TABLE PHIEUNHAP(
	MaPN VARCHAR(20) NOT NULL PRIMARY KEY,
	Ngay DATETIME,
	MaNCC VARCHAR(10) REFERENCES dbo.NHACUNGCAP,
	MaNV VARCHAR(10) REFERENCES dbo.NHANVIEN,
	MaTT VARCHAR(10) REFERENCES dbo.THANHTOAN,
	MaKho VARCHAR(10) REFERENCES dbo.KHO,
	TrangThaiXL NVARCHAR(10),
)

CREATE TABLE CHITIETPHIEU(
	MaPN VARCHAR(20) REFERENCES dbo.PHIEUNHAP,
	MaMH VARCHAR(10) REFERENCES dbo.MATHANG,
	SoLuong INT,
	HSD DATETIME,
	MaVT VARCHAR(10) REFERENCES dbo.VITRILUUTRU
)

CREATE TABLE DONHANG(
	MaDH VARCHAR(20) NOT NULL PRIMARY KEY,
	MaKH VARCHAR(10) REFERENCES dbo.KHACHHANG,
	MaTT VARCHAR(10) REFERENCES dbo.THANHTOAN,
	Ngay DATETIME,
	TrangThaiXL NVARCHAR(10),
)

CREATE TABLE CHITIETDONHANG(
	MaDH VARCHAR(20) REFERENCES dbo.DONHANG,
	MaMH VARCHAR(10) REFERENCES dbo.MATHANG,
	SoLuong INT,
)

CREATE TABLE MATHANGKHUYENMAI(
	MaMH VARCHAR(10) REFERENCES dbo.MATHANG,
	GiaTriKM FLOAT,
	NgayBD DATETIME,
	NgayKT DATETIME
)

CREATE TABLE CHIETKHAU(
	
)
CREATE TABLE TINHTHANH(
	MaTThanh VARCHAR(2) NOT NULL PRIMARY KEY,
)

CREATE TABLE QUANHUYEN(
	MaQH VARCHAR(2) NOT NULL PRIMARY KEY,
	MATThanh VARCHAR(2) REFERENCES dbo.TINHTHANH,
)

CREATE TABLE PHUONGXA(
	MaPX VARCHAR(3) NOT NULL PRIMARY KEY,
	MaQH VARCHAR(2) REFERENCES dbo.QUANHUYEN
)